# Generated by Django 3.1.1 on 2020-09-12 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('genre', '0001_initial'),
        ('user', '0007_auto_20200911_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMSeries',
            fields=[
                ('series_id', models.AutoField(primary_key=True, serialize=False)),
                ('series_title', models.CharField(max_length=30)),
                ('introduce', models.CharField(blank=True, max_length=1000, null=True)),
                ('paid_subscription', models.BooleanField(default=False)),
                ('last_uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tomag_num_total', models.PositiveIntegerField(default=0)),
                ('heart_num_total', models.PositiveIntegerField(default=0)),
                ('comment_num_total', models.PositiveIntegerField(default=0)),
                ('views_num_total', models.PositiveIntegerField(default=0)),
                ('series_genre', models.ManyToManyField(related_name='series_genre', to='genre.Genre')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tmauthor')),
            ],
        ),
        migrations.CreateModel(
            name='TMText',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_title', models.CharField(max_length=30)),
                ('main_sentence', models.CharField(blank=True, max_length=200, null=True)),
                ('text_content', models.CharField(max_length=5000)),
                ('heart_num', models.PositiveIntegerField(default=0)),
                ('comment_num', models.PositiveIntegerField(default=0)),
                ('views_num', models.PositiveIntegerField(default=0)),
                ('date_of_write', models.DateField(default=django.utils.timezone.now)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tomaggeul.tmseries')),
                ('text_genre', models.ManyToManyField(related_name='text_genre', to='genre.Genre')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tmauthor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_comment', models.DateField(default=django.utils.timezone.now)),
                ('comment_content', models.CharField(max_length=100)),
                ('is_report', models.BooleanField(default=False)),
                ('tmtext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomaggeul.tmtext')),
                ('tmuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
