# Generated by Django 3.1.1 on 2020-09-18 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('genre', '0001_initial'),
        ('tomaggeul', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tmtext',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tmauthor'),
        ),
        migrations.AddField(
            model_name='tmseries',
            name='series_genre',
            field=models.ManyToManyField(related_name='series_genre', to='genre.Genre'),
        ),
        migrations.AddField(
            model_name='tmseries',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tmauthor'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tmtext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tomaggeul.tmtext'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tmuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
