# Generated by Django 3.1.1 on 2020-09-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tmauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmauthor',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='portfolios'),
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='phone_number',
            field=models.CharField(default='010-1234-5678', max_length=11),
        ),
    ]
