# Generated by Django 3.1.1 on 2020-09-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200910_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='phone_number',
            field=models.CharField(default='010-1234-5678', max_length=13),
        ),
    ]
