# Generated by Django 3.1.1 on 2020-09-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200911_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmuser',
            name='nickname',
            field=models.CharField(error_messages={'unique': "'%(value)' is already exists %(field_label)."}, max_length=50, unique=True),
        ),
    ]
