# Generated by Django 3.1.1 on 2020-09-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200911_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmauthor',
            name='author_name',
            field=models.CharField(error_messages={'unique': '이미 존재하는 작가명입니다.'}, max_length=50, unique=True, verbose_name='작가명'),
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This is already exists %(field_label)s.'}, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'This is already exists %(field_label)s.'}, max_length=50, unique=True),
        ),
    ]
