# Generated by Django 3.1.1 on 2020-09-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200911_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmauthor',
            name='introduce',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tmauthor',
            name='page_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tmauthor',
            name='sns_link',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 존재하는 이메일입니다.'}, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tmuser',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 존재하는 닉네임입니다.'}, max_length=50, unique=True),
        ),
    ]
